version: "2"

services:
  hive-metastore-database:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db  
   
  hive-standalone-metastore:
    image: hhlai1990/hive-standalone-metastore:latest
    ports:
      - 9083:9083
    volumes:
      - /tmp/hive:/tmp/hive
    depends_on:
      - hive-metastore-database   
    command: ["/wait-for-it.sh", "hive-metastore-database:3306", "--", "/entrypoint.sh"]
  
  hue-database:
    image: mariadb:latest
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: hue    
    command: --init-file /data/application/init.sql
    volumes:
      - ./init_hue_mysql.sql:/data/application/init.sql    
      
  hue:
    image: gethue/hue:latest
    ports:
      - 8888:8888
    volumes:
      - ./hue.ini:/usr/share/hue/desktop/conf/hue.ini 
      - ./wait-for-it.sh:/wait-for-it.sh
    depends_on: 
      - hue-database
    command: ["/wait-for-it.sh", "hue-database:3306", "--", "./startup.sh"]

  spark-iceberg-server:
    build:
      context: .
      network: host
    image: spark-iceberg-server:latest
    ports:
    - 10000:10000
    volumes:
      - /tmp/hive:/tmp/hive
    depends_on:
      - hive-standalone-metastore
    command: ["/wait-for-it.sh", "hive-standalone-metastore:9083", "--", "/start-spark-iceberg-server.sh"]

